from typing import Dict, Set

lexems: Dict[str, str] = {
    "(": "LEFT_PAREN ( null",
    ")": "RIGHT_PAREN ) null",
    "{": "LEFT_BRACE { null",
    "}": "RIGHT_BRACE } null",
    ",": "COMMA , null",
    ".": "DOT . null",
    "*": "STAR * null",
    ";": "SEMICOLON ; null",
    "-": "MINUS - null",
    "+": "PLUS + null",
    "=": "EQUAL = null",
    "==": "EQUAL_EQUAL == null",
    "!=": "BANG_EQUAL != null",
    ">": "GREATER > null",
    "<": "LESS < null",
    ">=": "GREATER_EQUAL >= null",
    "<=": "LESS_EQUAL <= null",
    "!": "BANG ! null",
    "/": "SLASH / null",
    "and": "AND and null",
    "class": "CLASS class null",
    "else": "ELSE else null",
    "false": "FALSE false null",
    "for": "FOR for null",
    "fun": "FUN fun null",
    "if": "IF if null",
    "nil": "NIL nil null",
    "or": "OR or null",
    "print": "PRINT print null",
    "return": "RETURN return null",
    "super": "SUPER super null",
    "this": "THIS this null",
    "true": "TRUE true null",
    "var": "VAR var null",
    "while": "WHILE while null",
    "EOF": "EOF  null",
}

special: Set[str] = {"//", }
